# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_passwordresetcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='OWyyzhyjCXItgtk7L0ltGmmLrBTTwivRwn6huU8G7TJPNqMB', max_length=48),
        ),
    ]
