# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-16 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20230715_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='Sy0mQajXGvckBsYQ6xrzRJsgRp2Q2LxGzyKYNEK8L81yhbM7', max_length=48),
        ),
    ]
