# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-16 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20230716_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='8udCtglxsHpkDgL9xmelxywNULsRDPAx8IMCawPA9cwq8WDA', max_length=48),
        ),
    ]
