# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20230716_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=48),
        ),
    ]
